flowchart LR
    subgraph permissions
        direction LR
        change_role
        ban_user
        invite
        join
        leave
        message
    end
    subgraph roles
        direction LR
        admin
        moderator
        user
    end
        admin --- change_role
        moderator & admin --- invite
        moderator & admin --- ban_user
        user & admin --- join
        user & admin --- leave
        user & admin --- message
    subgraph users
        direction LR
        Alice --- admin
        Bob --- moderator
        John & Bob --- user
    end
